name: test2
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: composer install
        run: composer install
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Generate App Key
        run: php artisan key:generate
      - name: Create SQLite Database
        run: touch database/database.sqlite
      - name: Run Database Migrations
        run: php artisan migrate
      - name: Install npm dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Serve Application
        run: php artisan serve --host=0.0.0.0 --port=8000
